### PR TITLE
Improving tag filtering

### PR DESCRIPTION
**Pull request by twitterbirdwatch**
Additional tag filtering now better detects unexpected levels of "incorrect" tags.

### CODE REVIEW

**Comment by saifedinjn** [comment]
Thnx elon

**Comment by 9zmike** [comment]
Brilliant!

**Comment by sscornelius** [comment]
DIGITALSTARWORLD CO.

**Comment by Haseb-ali** [comment]
😃😃😃😃

**Comment by BoryantbodyA** [comment]
What's are the trending hashtags for this week @elonmusk

**Pull request merged**
