### PR TITLE
Move TSV readers to a separate module

### PR DESCRIPTION
**Pull request by yuvalbenarie**
The code is not separated enough by logic.
This PR extracts the file reading logic to a sub-module, and structures it a bit.

### CODE REVIEW

**Comment by yuvalbenarie** [comment]
Ran locally. Tests should probably be added to the repo.

**Comment by yuvalbenarie** [comment]
@bradmiller Rebased on top of your changes and adjusted my code accordingly.

**Comment by yuvalbenarie** [comment]
@lucasnantonio I rebased again after https://github.com/twitter/communitynotes/pull/74 was merged.
The willingness to receive contributions and engage with the open-source community on this repo is pretty disappointing so far, I must say.
More than one-liners are not getting looked at, while internal contributions are being merged making already open PRs rot.

**Comment by lucasnantonio** [comment]
@yuvalbenarie thanks for your contribution. 

Our eng team is currently heads down on an important upcoming launch and will review open PRs as soon as possible. 
We may not be able to review all contributions in real time, as there are systems tests and other internal analyses we need to perform with each change.

Appreciate your understanding.

cc @bradmiller @jbaxter

**Comment by bradmiller** [comment]
Hi @yuvalbenarie  - Thanks for the PR.  As @lucasnantonio mentioned, we're heavily focused right now on an upcoming launch, which is taking up eng time.  I tested the PR, but part of the challenge with integrating is that tsv_parser and tsv_reader are used elsewhere in the internal codebase, which makes removing them more complicated.

-Brad

**Comment by yuvalbenarie** [comment]
Thanks, @bradmiller. It is indeed very helpful to understand the bigger picture. I was not aware code in this repo was used elsewhere, as it is not modeled and implemented as a python package.
I have modified the code to be backward compatible and extended the capabilities of the new readers, so they can be used to implement all existing functionality.
I also added tests (using the `pytest` package) that I ran locally to verify the expected behavior.
 It would be great if python testing would be added to the CI later on.

**Comment by yuvalbenarie** [comment]
Just read the updated README. Feel free to close this PR if code-quality PRs are currently not relevant.

**Comment by jbaxter** [comment]
@yuvalbenarie I'm closing this for now due to above-mentioned reasons but really appreciate you taking the time to write such a great diff and hope we can incorporate it in the future.

**Pull request closed without merging**
